apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dest-docker-config
  namespace: product-catalog-cicd
spec:
  encryptedData:
    .dockerconfigjson: XXXXXXXXXXXXXXXXXXXXX
  template:
    metadata:
      name: dest-docker-config
      namespace: product-catalog-cicd
    type: kubernetes.io/dockerconfigjson